name: Documentation
description: Unclear, missing, or incorrect documentation
labels: ['documentation']
body:
  - type: input
    id: location
    attributes:
      label: Location
      description: Which page or section?
      placeholder: README, "Usage" section
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is wrong or missing?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested wording
